### ISSUE TITLE
Directories with spaces are sometimes completed incorrectly

### ISSUE THREAD

**Issue by kolayne** [sio/bash-complete-partial-path#23]
In some cases (apparently, when tab is used in a path prefix that ends with a slash) a directory with a space in its name is considered by completion as two directories. Demo: https://asciinema.org/a/549127

**Comment by sio** [comment]
Thank you for reporting this and the other issue. I am currently on a holiday break and will review your reports and PR after January 15th.

**Comment by sio** [comment]
Fixed and merged into master
