### ISSUE TITLE
Do not change readline configuration

### ISSUE THREAD

**Issue by marcelpaulo** [sio/bash-complete-partial-path#4]
If you allow me a suggestion, do not change readline configuration. Those changes don't seem to be required for partial completion to work, even though, as you commented, they may provide a _"better user experience"_. They're sensible changes, but they may disrupt what one is used to about readline.

For instance, I don't like to have `menu-complete` bound to `TAB`, I prefer `complete`, with `set show-all-if-ambiguous on`. So, after I tried partial completion for the first time, my first reaction was: _hey, this is really great, but why the list of possible completions is not shown anymore ?!_. I then looked at your code, and saw that you changed readline configuration. But then again, this is my personal preference.

Changing readline configuration from _bash_completion_ may be a beneficial or a disruptive side effect, depending on how one uses readline. But it will be a side effect.

IMO, I would remove it from _bash_completion_, and suggest them in the installation instructions.

**Comment by marcelpaulo** [comment]
I was checking my _~/.inputrc_, and found out that I have all your settings but these:

```
bind 'TAB:menu-complete'                                                                                                                                                                          
bind 'set menu-complete-display-prefix on'                                                                                                                                                        
```

Exactly the ones related to `menu-complete`.

**Comment by sio** [comment]
I agree it's a valid suggestion. I think I'll move the recommended (but
optional) settings into a separate function that doesn't get called by
default.

That way it'll be easy to invoke (just one more line in bashrc) for those
who want my defaults, yet not forced on anybody.

Unfortunately, I'm on vacation and will be at my computer after July, 30th.
I'll get back to this issue then.

Thank you for your feedback! And thank you for taking an interest in this
project

**Comment by marcelpaulo** [comment]
It's a really useful project you have started, my congratulations.

> I think I'll move the recommended (but optional) settings into a separate function that doesn't get called by default

Excellent idea, I hadn't thought of that.

**Comment by marcelpaulo** [comment]
I'm impressed by what you implemented: it's better than what I initially imagined, by very far ! You really made life easy for the users of your software.

> thank you for the idea

The idea and merit is all yours !
