### ISSUE TITLE
Feature: Add a way to go to the previous suggestion

### ISSUE THREAD

**Issue by geekscrapy** [sio/bash-complete-partial-path#9]
Any way to work in a way to go back to a previous item if you go past it by accident?
Thinking like when you alt+tab in Windows, you can alt+shift+tab to go back.

No idea if its possible, but I thought I'd ask!

**Comment by sio** [comment]
It's already implemented. If you use `_bcpp --defaults`, Shift+Tab circles back to previous suggestion:
https://github.com/sio/bash-complete-partial-path/blob/11771a516769e17c02314300ae98d586171f7a6b/bash_completion#L318-L323

I'll leave this issue open for a while to maybe add that to documentation in some way.

**Comment by geekscrapy** [comment]
Yup, I've upgraded the bash version and now it works 👍
